### PR TITLE
Use method 'POST'

### PR DESCRIPTION
**Pull request by jpfundsr**
Default method 'PUT' was resulting in 403 forbidden responses.

### CODE REVIEW

**Comment by jpfundsr** [comment]
Just noticed the 'PUT' method PR already merged.  This likely solves our issue as well.

**Comment by Auoja** [comment]
I have not had time to investigate this issue fully tbh. I no longer use this package on a daily basis since I am working on some other projects. I will try to get back into it next week if I have some time.

**Comment by hadfieldn** [comment]
@jpfundsr PUT does seem to work (for now anyway), but you're correct that this should really be a POST instead. My bad.

**Comment by hadfieldn** [comment]
And @Auoja thanks for this module. We do use it heavily on a daily basis. :-)

**Pull request closed without merging**
